version: ‘3’
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    # networks:
    # - inception
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env                
    volumes:
      - ./requirements/mariadb/db:/var/lib/mysql
    restart: unless-stopped
    expose:
      - 3306