# Variables can be set in .env file:
#   BUILD_TYPE: privileged (default) or rootless
#   NGINX_PORT: 443 (default)
#version: 3
services:
  mariadb:
    image: mariadb-${BUILD_TYPE:-privileged}
    container_name: mariadb-${BUILD_TYPE:-privileged}
    build:
      context: ./requirements/mariadb
      target: "${BUILD_TYPE:-privileged}"
    env_file: .env
    volumes:
      - ./requirements/mariadb/db:/var/lib/mysql
    restart: unless-stopped
    expose:
      - 3306
    # ports:
    #   - 3306:3306
  nginx:
    image: nginx-${NGINX_PORT:-443}
    container_name: nginx-${NGINX_PORT:-443}
    build:
      context: ./requirements/nginx
    env_file: .env
    restart: unless-stopped
    ports:
      - ${NGINX_PORT:-443}:443
  wordpress:
    image: wordpress-${BUILD_TYPE:-privileged}-${NGINX_PORT:-443}
    container_name: wordpress-${BUILD_TYPE:-privileged}-${NGINX_PORT:-443}
    build:
      context: ./requirements/wordpress
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}