# Variables can be set in .env file:
#   BUILD_TYPE: privileged (default) or rootless
#   NGINX_PORT: 443 (default)

version: "3"
services:
  mariadb:
    image: mariadb-${BUILD_TYPE:-privileged}
    container_name: mariadb-${BUILD_TYPE:-privileged}
    build:
      context: ./requirements/mariadb
      target: "${BUILD_TYPE:-privileged}"
    env_file: .env
    volumes:
      - ${DB_VOLUME:-"./requirements/mariadb/db"}:/var/lib/mysql
    expose:
      - 3306
    restart: unless-stopped
    networks:
      - inception_bridge
    # ports:
    #   - 3306:3306

  wordpress:
    depends_on:
      - mariadb
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=mariadb-${BUILD_TYPE:-privileged}:3306
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
    restart: unless-stopped
    networks:
      - inception_bridge
    volumes:
      - ${WEBSITE_VOLUME:-"./requirements/wordpress/web_site"}:/var/www/html

  nginx:
    depends_on:
      - wordpress
    image: nginx-${NGINX_PORT:-443}
    container_name: nginx-${NGINX_PORT:-443}
    build:
      context: ./requirements/nginx
    env_file: .env
    restart: unless-stopped
    volumes:
      - ${WEBSITE_VOLUME:-"./requirements/wordpress/web_site"}:/var/www/html
    networks:
      - inception_bridge
    ports:
      - ${NGINX_PORT:-443}:443

networks:
  inception_bridge:
    driver: bridge