# Variables can be set in .env file:
#   BUILD_TYPE: production (default) or rootless
#   NGINX_PORT: 443 (default)
version: ‘3’
services:
  mariadb:
    image: mariadb-${BUILD_TYPE:-production}
    container_name: mariadb-${BUILD_TYPE:-production}
    build:
      context: ./requirements/mariadb
      target: "${BUILD_TYPE:-production}"
    env_file: .env
    volumes:
      - ./requirements/mariadb/db:/var/lib/mysql
    restart: unless-stopped
    expose:
      - 3306
    # ports:
    #   - 3306:3306
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
    env_file: .env
    restart: unless-stopped
    ports:
      - ${NGINX_PORT:-443}:443